pipeline {
    agent any
    environment {
        VENV_PATH = "./.venv"
        PYTHON_INTERPRETER = "${VENV_PATH}/bin/python3"
    }
    stages {
        stage('Setup Environment') {
            steps {
               sh '''
                   #!/bin/bash
                   virtualenv .venv
                   . .venv/bin/activate
                   pip install -r lab2/requirements.txt
                   echo 'OK'
                   '''
               }
            }
        stage('Generate data') {
            steps {
                echo 'Start generate data'
                sh "${PYTHON_INTERPRETER} lab2/data_creation.py"
                echo 'OK'
            }
        }
        stage('Preprocess model') {
            steps {
                echo 'Start preprocessing model'
                sh "${PYTHON_INTERPRETER} lab2/model_preprocessing.py"
                echo 'OK'
            }
        }
        stage('Preparation model') {
            steps {
                echo 'Start preparation model'
                sh "${PYTHON_INTERPRETER} lab2/model_preparation.py"
                echo 'OK'
            }
        }
        stage('Test model') {
            steps {
                echo 'Start test model'
                sh "${PYTHON_INTERPRETER} lab2/model_testing.py"
                echo 'OK'
            }
        }
}
}



