pipeline {
    agent any
    stages {
        stage('Setup Environment') {
            steps {
               sh '''
                   #!/bin/bash
                   virtualenv .venv
                   . .venv/bin/activate
                   pwd
                   chmod u+r requirements.txt
                   pip install -r requirements.txt
                   '''
               }
            }
        stage('Generate data') {
            steps {
                echo 'Start generate data'
                sh "python3 ./data_creation.py"
                echo 'OK'
            }
        }
        stage('Preprocess model') {
            steps {
                echo 'Start preprocessing model'
                sh "python3 ./data_preprocessing.py"
                echo 'OK'
            }
        }
        stage('Preparation model') {
            steps {
                echo 'Start preparation model'
                sh "python3 ./data_preparation.py"
                echo 'OK'
            }
        }
        stage('Test model') {
            steps {
                echo 'Start test model'
                sh "python3 ./data_preparation.py"
                echo 'OK'
            }
        }
}
}



